function test_baseline_monte_carlo_configuration()
%TEST_BASELINE_MONTE_CARLO_CONFIGURATION Audit local baseline validation.

projectDir = fileparts(fileparts(mfilename('fullpath')));
runnerText = string(fileread(fullfile(projectDir,'scripts', ...
    'run_reviewer2_baseline_monte_carlo.m')));
plotText = string(fileread(fullfile(projectDir,'scripts', ...
    'plot_reviewer2_baseline_monte_carlo.m')));

requiredRunner = string({ ...
    'addParameter(p,''Mission'',"LOW_THRUST_TRANSFER")', ...
    'addParameter(p,''Measurement'',"ANGLES_ONLY")', ...
    'addParameter(p,''ObserverCounts'',[3 5 7 10])', ...
    'addParameter(p,''Samples'',250)', ...
    'addParameter(p,''OrbitPerturbation'',10)', ...
    'addParameter(p,''SlotPerturbation'',5)', ...
    'reviewer2_baseline_v1', ...
    'height(group) == 20', ...
    '[~,idx] = min(group.BestObjective)', ...
    'designs(1,:)', ...
    'randi(stream,[-orbitRadius orbitRadius]', ...
    'randi(stream,[-slotRadius slotRadius]', ...
    'objective_wrapper', ...
    'baseline_monte_carlo_', ...
    'baseline_monte_carlo_samples.csv', ...
    'baseline_monte_carlo_summary.csv', ...
    'plot_reviewer2_baseline_monte_carlo'});
assert_tokens(runnerText,requiredRunner,'Baseline Monte Carlo runner');

requiredPlot = string({ ...
    'boxchart', ...
    'ReferenceObjective', ...
    '''MC samples''', ...
    '''Total cost''', ...
    'baseline_mc_', ...
    'print(fig,[base ''.eps''],''-depsc2'',''-painters'',''-r600'')', ...
    'enforce_minimum_font_size(fig,12)'});
assert_tokens(plotText,requiredPlot,'Baseline Monte Carlo plotter');

fprintf('Baseline Monte Carlo configuration passed.\n');
end


function assert_tokens(textValue,tokens,label)
for token = tokens
    assert(contains(textValue,token), ...
        '%s is missing required token: %s',label,token);
end
end