function test_reviewer2_legend_configuration()
%TEST_REVIEWER2_LEGEND_CONFIGURATION Audit manuscript legend behavior.
projectDir = fileparts(fileparts(mfilename('fullpath')));
legendText = string(fileread(fullfile(projectDir,'scripts','format_manuscript_legend.m')));
centerText = string(fileread(fullfile(projectDir,'scripts','center_manuscript_content.m')));
styleText = string(fileread(fullfile(projectDir,'scripts','reviewer2_paper_style.m')));
studyText = string(fileread(fullfile(projectDir,'scripts','plot_study_definition_figures.m')));
curatedText = string(fileread(fullfile(projectDir,'scripts','make_reviewer2_curated_figures.m')));
geometryText = string(fileread(fullfile(projectDir,'scripts','plot_reviewer2_geometry_grid.m')));
parallelText = string(fileread(fullfile(projectDir,'scripts','plot_parallel_speed.m')));

requiredLegend = [ ...
    "contextual_legend_labels", ...
    "is3D = abs(ax.View(2)-90) > 1e-8", ...
    "plotPosition = style.geometryPlotPosition", ...
    "plotPosition = style.metricPlotPosition", ...
    "lgd.FontSize = style.geometryLegendFontSize", ...
    "lgd.FontSize = style.legendFontSize", ...
    "lgd.Orientation = 'horizontal'", ...
    "columns = min(numel(labels),style.legendMaxColumns)", ...
    "while lgd.Position(3) > style.legendMaxWidth && columns > 1", ...
    "lgd.Location = 'none'", ...
    "pos(1) = 0.5-pos(3)/2", ...
    "pos(2) = plotPosition(2)+plotPosition(4)+legendGap", ...
    "ax.Position = plotPosition", ...
    "format_manuscript_ticks(ax)", ...
    "center_manuscript_content(fig,ax,lgd)", ...
    "labels(labels == \"Observer orbits\") = \"Obs.\"", ...
    "labels(labels == \"Endpoint orbits\") = \"Endpt.\"", ...
    "labels(labels == \"Target trajectory\") = \"LG\""];
assert_tokens(legendText,requiredLegend,'Manuscript legend formatter');

requiredCenter = [ ...
    "legendPosition(1) = 0.5*(figureWidth-legendPosition(3))", ...
    "inset = ax.TightInset", ...
    "axesLeft = axesPosition(1)-inset(1)", ...
    "axesRight = axesPosition(1)+axesPosition(3)+inset(3)", ...
    "imbalance = @(dx) content_imbalance", ...
    "leftMargin = contentLeft", ...
    "rightMargin = figureWidth-contentRight", ...
    "axesPosition(1) = axesPosition(1)+dx"];
assert_tokens(centerText,requiredCenter,'Final manuscript content centering');

assert(~contains(legendText,'if is3D\n    center_manuscript_content'), ...
    'Final content centering must apply to both 2-D and 3-D figures.');
assert(~contains(legendText,'labels(labels == "L1 point") = "L1"') && ...
    ~contains(legendText,'labels(labels == "L2 point") = "L2"'), ...
    'Orbit-database legends must preserve explicit L1 point/L2 point labels.');
assert(contains(styleText,'style.legend2DGap = 0.08'), ...
    '2-D legends need a consistent gap above the axes/labels.');
assert(contains(styleText,'style.geometryLegendGap = -0.04'), ...
    '3-D legends should sit close to the trajectory axes.');
assert(contains(styleText,'style.legendFontSize = 14') && ...
    contains(styleText,'style.geometryLegendFontSize = 15'), ...
    '2-D and 3-D legend font sizes must be centrally configured.');
assert(contains(studyText,'format_manuscript_legend(ax,legendHandle,style,plotPosition)'), ...
    'Study-definition 3-D figures must use the shared legend formatter.');
assert(contains(curatedText,'format_manuscript_legend(ax,lgd,style,style.metricPlotPosition)'), ...
    'Curated 2-D figures must use the shared legend formatter.');
assert(contains(geometryText,'format_manuscript_legend(ax,lgd,style,plotPosition)'), ...
    'Representative geometry figures must use the shared legend formatter.');
assert(contains(parallelText,'format_manuscript_legend(ax,lgd,style,style.metricPlotPosition)'), ...
    'Parallel figures must use the same 2-D legend formatter.');

fprintf('Reviewer 2 legend/content-centering configuration passed.\n');
end

function assert_tokens(textValue,tokens,label)
for token = tokens
    assert(contains(textValue,token), ...
        '%s is missing required token: %s',label,token);
end
end
