function test_ga_objective_screening_configuration()
%TEST_GA_OBJECTIVE_SCREENING_CONFIGURATION Audit the GA sensitivity study.

projectDir = fileparts(fileparts(mfilename('fullpath')));
studyText = string(fileread(fullfile( ...
    projectDir,'scripts','batch','run_ga_objective_screening_soo.ps1')));

requiredCommon = [ ...
    '$StudyId = "reviewer2_ga_objective_screening_v1"', ...
    '$StudyFolder = "GA_OBJECTIVE_SCREENING"', ...
    '[int]$EvalBudget = 6000', ...
    '[int[]]$Seeds = (0..19)', ...
    '$env:OPTIMIZER_MODE = "GA"', ...
    '$env:USE_PARALLEL_OPT = "1"', ...
    '$env:MEAS_MODEL = "ANGLES_ONLY"', ...
    '$env:NUM_OBSERVERS = "3"', ...
    '$env:NPERIODS = "1"', ...
    '$env:MEAS_NOISE_SEED = "$MeasurementNoiseSeed"', ...
    '$MeasurementNoiseSeed = 1001', ...
    '$MissionTypes = @("LUNAR_GATEWAY", "LOW_THRUST_TRANSFER", "GATEWAY_IMPULSE")', ...
    '$TotalRuns = $Cases.Count * $MissionTypes.Count * $Seeds.Count', ...
    '_INCOMPLETE_RUNS', ...
    'Skipping completed run'];

for token = requiredCommon
    assert(contains(studyText,token), ...
        'GA objective/screening study is missing required token: %s',token);
end

% Match the five rows of the original comparison-study configuration table.
requiredCases = [ ...
    'Code = "combined_on"', ...
    'Label = "Combined objective with screening"', ...
    'Code = "combined_off"', ...
    'Label = "Combined objective without screening"', ...
    'Code = "j1_only"', ...
    'Label = "Estimation-error only"', ...
    'Code = "j2_only"', ...
    'Label = "Uncertainty only"', ...
    'Code = "j3_only"', ...
    'Label = "Stability only"'];
for token = requiredCases
    assert(contains(studyText,token), ...
        'GA objective/screening study is missing original-table case: %s',token);
end

% Inspect each case block rather than accepting the right labels with the
% wrong screening/objective switches.
casePatterns = [ ...
    'Code = "combined_on"(?s).*?Screening = 1(?s).*?J1 = 1(?s).*?J2 = 1(?s).*?J3 = 1', ...
    'Code = "combined_off"(?s).*?Screening = 0(?s).*?J1 = 1(?s).*?J2 = 1(?s).*?J3 = 1', ...
    'Code = "j1_only"(?s).*?Screening = 1(?s).*?J1 = 1(?s).*?J2 = 0(?s).*?J3 = 0', ...
    'Code = "j2_only"(?s).*?Screening = 1(?s).*?J1 = 0(?s).*?J2 = 1(?s).*?J3 = 0', ...
    'Code = "j3_only"(?s).*?Screening = 1(?s).*?J1 = 0(?s).*?J2 = 0(?s).*?J3 = 1'];
for pattern = casePatterns
    assert(~isempty(regexp(studyText,pattern,'once')), ...
        'A GA sensitivity case has incorrect screening/objective switches.');
end

% Only the combined-objective OFF case should disable screening.
assert(count(studyText,'Screening = 0') == 1, ...
    'Exactly one study configuration should disable screening.');

% Full study: 5 cases x 3 missions x 20 seeds = 300 optimization runs.
assert(5*3*20 == 300);

fprintf('GA objective/screening study configuration passed.\n');
end
