function test_runtime_pipeline_configuration()
%TEST_RUNTIME_PIPELINE_CONFIGURATION Audit the focused 1200-FE processor.

projectDir = fileparts(fileparts(mfilename('fullpath')));
pipelineText = string(fileread(fullfile( ...
    projectDir,'scripts','run_reviewer2_runtime_pipeline.m')));
launcherText = string(fileread(fullfile( ...
    projectDir,'scripts','batch','run_runtime_comparison_1200_soo.ps1')));

requiredPipeline = [ ...
    'budget = 1200', ...
    'seeds = 0:19', ...
    'optimizers = ["GA","PSO","BAYESIAN","ABC","ACO"]', ...
    'mission = "LUNAR_GATEWAY"', ...
    'reviewer2_runtime_comparison_1200_v1', ...
    'RUNTIME_COMPARISON_1200', ...
    'process_fe_convergence', ...
    'expectedRuns = numel(optimizers)*numel(seeds)', ...
    'plotStartFE = 60', ...
    'build_bo_slowdown', ...
    'plot_runtime_convergence', ...
    'plot_runtime_bar', ...
    'plot_objective_bar', ...
    'runtime_comparison_1200_bo_audit.csv'];

for token = requiredPipeline
    assert(contains(pipelineText,token), ...
        'Runtime processing pipeline is missing required token: %s',token);
end

requiredLauncher = [ ...
    '$Algs = @("GA", "PSO", "BAYESIAN", "ABC", "ACO")', ...
    '$EvalBudget = 1200', ...
    '$MissionType = "LUNAR_GATEWAY"', ...
    '$MeasModel = "ANGLES_ONLY"', ...
    '$NumObservers = 3', ...
    '$NPeriods = 1', ...
    '$TotalRuns = $Algs.Count * $Seeds.Count'];

for token = requiredLauncher
    assert(contains(launcherText,token), ...
        'Runtime launcher is missing required token: %s',token);
end

fprintf('Runtime pipeline configuration passed.\n');
end
