function test_reviewer2_paper_figures_configuration()
%TEST_REVIEWER2_PAPER_FIGURES_CONFIGURATION Audit manuscript figure layout.
projectDir = fileparts(fileparts(mfilename('fullpath')));
styleText = string(fileread(fullfile(projectDir,'scripts','reviewer2_paper_style.m')));
studyText = string(fileread(fullfile(projectDir,'scripts','plot_study_definition_figures.m')));
curatedText = string(fileread(fullfile(projectDir,'scripts','make_reviewer2_curated_figures.m')));
parallelText = string(fileread(fullfile(projectDir,'scripts','plot_parallel_speed.m')));
barText = string(fileread(fullfile(projectDir,'scripts','space_manuscript_bars.m')));
tickText = string(fileread(fullfile(projectDir,'scripts','format_manuscript_ticks.m')));
wrapText = string(fileread(fullfile(projectDir,'scripts','wrap_manuscript_label.m')));
abbrevText = string(fileread(fullfile(projectDir,'scripts','abbreviate_manuscript_text.m')));
runnerText = string(fileread(fullfile(projectDir,'run_manuscript_figures.m')));
tableText = string(fileread(fullfile(projectDir,'print_manuscript_tables.m')));

requiredStyle = [ ...
    "style.fontSize = 16", ...
    "style.labelFontSize = 18", ...
    "style.legendFontSize = 14", ...
    "style.geometryLegendFontSize = 15", ...
    "style.figureWidth = 6.5", ...
    "style.figureHeight = 5.2", ...
    "style.metricFigureWidth = style.figureWidth", ...
    "style.geometryFigureWidth = style.figureWidth", ...
    "style.measurementFigureWidth = style.figureWidth", ...
    "style.visibilityFigureWidth = style.figureWidth", ...
    "style.monteCarloFigureWidth = style.figureWidth", ...
    "style.metricPlotPosition = [0.15 0.17 0.82 0.56]", ...
    "style.legend2DGap = 0.08", ...
    "style.geometryPlotPosition = [0.10 0.14 0.80 0.70]", ...
    "style.geometryLegendGap = -0.04", ...
    "style.geometryXPadding = 0.04", ...
    "style.geometryYPadding = 0.05", ...
    "style.geometryZPadding = 0.05", ...
    "style.groupedBarWidth = 0.64", ...
    "style.categoryLabelAngle = 30"];
assert_tokens(styleText,requiredStyle,'Shared manuscript style');

% Every compatibility size alias must resolve to the one standard canvas.
for token = [ ...
        "style.metricFigureHeight = style.figureHeight", ...
        "style.convergenceFigureHeight = style.figureHeight", ...
        "style.geometryFigureHeight = style.figureHeight", ...
        "style.orbitFamilyFigureHeight = style.figureHeight", ...
        "style.slotPhaseFigureHeight = style.figureHeight", ...
        "style.visibilityFigureHeight = style.figureHeight", ...
        "style.measurementFigureHeight = style.figureHeight", ...
        "style.monteCarloFigureHeight = style.figureHeight"]
    assert(contains(styleText,token),'Nonstandard manuscript canvas alias: %s',token);
end

% RA and Dec remain matched.
assert(count(studyText,'style.measurementFigureWidth,style.measurementFigureHeight') >= 2, ...
    'RA/Dec figures must use the same outer manuscript canvas.');
assert(count(studyText,"Position',[0.10,0.12,0.82,0.80]") >= 2, ...
    'RA/Dec figures must use the same axes rectangle.');
assert(count(studyText,'xlim(ax1,[-0.95,5.10])') == 1 && ...
    count(studyText,'xlim(ax2,[-0.95,5.10])') == 1 && ...
    count(studyText,'ylim(ax1,[-0.80,4.20])') == 1 && ...
    count(studyText,'ylim(ax2,[-0.80,4.20])') == 1, ...
    'RA/Dec figures must use matched plotting limits.');

% EPS export remains the proven non-mutating painters print path.
assert(contains(studyText,"print(fig,char(fileName),'-depsc2','-painters','-r600')"), ...
    'Study-definition EPS export path changed unexpectedly.');
assert(contains(curatedText,"print(fig,[base '.eps'],'-depsc2','-painters','-r600')"), ...
    'Result EPS export path changed unexpectedly.');
assert(contains(parallelText,'style.figureWidth style.figureHeight') && ...
    contains(parallelText,'format_manuscript_legend'), ...
    'Parallel figures must use the common canvas and legend formatter.');

assert(contains(tickText,'keep = [1 3]') && ...
    contains(tickText,'span <= 0.15') && ...
    contains(tickText,'keep = [1 numel(ticks)]'), ...
    '3-D tick formatter must remove central zero and thin crowded small-range axes.');
assert(contains(barText,'numel(labels) >= 8') && ...
    contains(barText,'style.categoryLabelAngle'), ...
    'Dense family-comparison optimizer labels need explicit rotation.');
assert(contains(barText,'p(2) = p(2) + 0.02*yRange'), ...
    'LG/LT/GI family-group labels must move slightly upward.');
assert(contains(wrapText,'maxChars = 32') && ...
    contains(wrapText,'abbreviate_manuscript_text'), ...
    'Duration labels must abbreviate before wrapping to avoid EPS cutoff.');
assert(contains(abbrevText,'Effective position sigma (km)') && ...
    contains(abbrevText,'Position RMSE (km)'), ...
    'Long metric labels must be shortened before layout.');

% One root-level entry point produces figures and the LaTeX table printout.
assert(contains(runnerText,'print_manuscript_tables') && ...
    contains(runnerText,'plot_study_definition_figures_for_manuscript') && ...
    contains(runnerText,'make_reviewer2_final_figures'), ...
    'run_manuscript_figures must consolidate definition, result, and table generation.');
assert(contains(tableText,'manuscript_tables.tex') && ...
    contains(tableText,'manuscript_tables.txt'), ...
    'Table printer must save copyable LaTeX and text output.');

fprintf('Reviewer 2 manuscript figure configuration passed.\n');
end

function assert_tokens(textValue,tokens,label)
for token = tokens
    assert(contains(textValue,token), ...
        '%s is missing required token: %s',label,token);
end
end
