function test_baseline_monte_carlo_configuration()
%TEST_BASELINE_MONTE_CARLO_CONFIGURATION Audit local baseline validation.

projectDir = fileparts(fileparts(mfilename('fullpath')));
runnerText = string(fileread(fullfile(projectDir,'scripts', ...
    'run_reviewer2_baseline_monte_carlo.m')));
plotText = string(fileread(fullfile(projectDir,'scripts', ...
    'plot_reviewer2_baseline_monte_carlo.m')));

requiredRunner = string({ ...
    'addParameter(p,''Mission'',\["LOW_THRUST_TRANSFER","LUNAR_GATEWAY","GATEWAY_IMPULSE"\])', ...
    'opts.Mission = upper(string(opts.Mission(:)''))', ...
    'for mission = opts.Mission', ...
    'allRuns.Mission == mission', ...
    'addParameter(p,''Measurement'',"ANGLES_ONLY")', ...
    'addParameter(p,''ObserverCounts'',[3 5 7 10])', ...
    'addParameter(p,''GatewayPeriods'',[1 3 5])', ...
    'addParameter(p,''Samples'',250)', ...
    'addParameter(p,''OrbitPerturbation'',10)', ...
    'addParameter(p,''SlotPerturbation'',5)', ...
    'reviewer2_baseline_v1', ...
    'height(group) == 20', ...
    '[~,idx] = min(group.BestObjective)', ...
    'designs(1,:)', ...
    'randi(stream,[-orbitRadius orbitRadius]', ...
    'randi(stream,[-slotRadius slotRadius]', ...
    'objective_wrapper', ...
    'COMPILED_REVIEWER_2_RESULTS', ...
    'baseline_monte_carlo_', ...
    'baseline_monte_carlo_samples.csv', ...
    'baseline_monte_carlo_summary.csv', ...
    'plot_reviewer2_baseline_monte_carlo'});
requiredRunner(1) = erase(requiredRunner(1),'\');
assert_tokens(runnerText,requiredRunner,'Baseline Monte Carlo runner');

requiredPlot = string({ ...
    'hBox = boxchart', ...
    'hRef = yline', ...
    'ReferenceObjective', ...
    'plotValues = [double(rows.TotalCost(:));double(s.ReferenceObjective)]', ...
    'plotSpan = max(plotMax-plotMin,0.05*max(1,max(abs(plotValues))))', ...
    'yPadding = 0.08*plotSpan', ...
    'ylim(ax,[plotMin-yPadding,plotMax+yPadding])', ...
    'style.monteCarloFigureWidth', ...
    'style.monteCarloFigureHeight', ...
    '''PaperSize'',[widthIn heightIn]', ...
    '''PaperPosition'',[0 0 widthIn heightIn]', ...
    'figureDir = string(fullfile(char(outDir),''figures''))', ...
    'base = fullfile(char(figureDir),char(stem))', ...
    'details.FigureDirectory = repmat(figureDir,height(details),1)', ...
    '''Monte Carlo samples''', ...
    '''Objective value''', ...
    'legend(ax,[hBox hRef],{''Monte Carlo samples'',''Optimized reference''}', ...
    '''Location'',''northoutside''', ...
    'box(ax,''off'')', ...
    'grid(ax,''off'')', ...
    '''Box'',''off''', ...
    '''XGrid'',''off''', ...
    'baseline_mc_', ...
    'print(fig,[base ''.eps''],''-depsc2'',''-painters'',''-r600'')', ...
    'enforce_minimum_font_size(fig,12)'});
assert_tokens(plotText,requiredPlot,'Baseline Monte Carlo plotter');
assert(~contains(plotText,'title(') && ~contains(plotText,'sgtitle('), ...
    'Monte Carlo manuscript exports must not contain embedded titles.');
assert(~contains(plotText,'''Position'',[1 1 4.8 4.2]') && ...
    ~contains(plotText,'''PaperSize'',[4.8 4.2]'), ...
    'Monte Carlo sizing must come from reviewer2_paper_style.');
assert(~contains(plotText,'''Total cost''') && ~contains(plotText,'''MC samples'''), ...
    'Monte Carlo axes/legend must use clear, unabbreviated labels.');
assert(~contains(plotText,'''HandleVisibility'',''off'');'), ...
    'Optimized-reference line must remain visible to the Monte Carlo legend.');
assert(~contains(plotText,'box(ax,''on'')') && ~contains(plotText,'grid(ax,''on'')'), ...
    'Monte Carlo figures must not enable axes boxes or grid lines.');

fprintf('Baseline Monte Carlo configuration passed.\n');
end


function assert_tokens(textValue,tokens,label)
for token = tokens
    assert(contains(textValue,token), ...
        '%s is missing required token: %s',label,token);
end
end
