function test_reviewer2_paper_figures_configuration()
%TEST_REVIEWER2_PAPER_FIGURES_CONFIGURATION Audit manuscript figure layout.
projectDir = fileparts(fileparts(mfilename('fullpath')));
styleText = string(fileread(fullfile(projectDir,'scripts','reviewer2_paper_style.m')));
studyText = string(fileread(fullfile(projectDir,'scripts','plot_study_definition_figures.m')));
curatedText = string(fileread(fullfile(projectDir,'scripts','make_reviewer2_curated_figures.m')));
geometryGridText = string(fileread(fullfile(projectDir,'scripts','plot_reviewer2_geometry_grid.m')));
parallelText = string(fileread(fullfile(projectDir,'scripts','plot_parallel_speed.m')));
barText = string(fileread(fullfile(projectDir,'scripts','space_manuscript_bars.m')));
tickText = string(fileread(fullfile(projectDir,'scripts','format_manuscript_ticks.m')));
wrapText = string(fileread(fullfile(projectDir,'scripts','wrap_manuscript_label.m')));
abbrevText = string(fileread(fullfile(projectDir,'scripts','abbreviate_manuscript_text.m')));
finalizerText = string(fileread(fullfile(projectDir,'scripts','finalize_manuscript_figure.m')));
centerText = string(fileread(fullfile(projectDir,'scripts','center_manuscript_content.m')));
legendText = string(fileread(fullfile(projectDir,'scripts','format_manuscript_legend.m')));
legendColumnsText = string(fileread(fullfile(projectDir,'scripts','manuscript_legend_columns.m')));
runnerText = string(fileread(fullfile(projectDir,'run_manuscript_figures.m')));
tableText = string(fileread(fullfile(projectDir,'print_manuscript_tables.m')));

requiredStyle = [ ...
    "style.fontSize = 20", ...
    "style.labelFontSize = 23", ...
    "style.geometryFontSize = 22", ...
    "style.geometryLabelFontSize = 24", ...
    "style.legendFontSize = 20", ...
    "style.geometryLegendFontSize = 21", ...
    "style.sharedLegendFontSize = 22", ...
    "style.sharedLegendFigureHeight = 1.05", ...
    "style.sharedGeometryLegendWidth = 3.10", ...
    "style.sharedGeometryLegendHeight = 1.05", ...
    "style.figureWidth = 6.5", ...
    "style.figureHeight = 5.2", ...
    "style.metricFigureWidth = style.figureWidth", ...
    "style.geometryFigureWidth = style.figureWidth", ...
    "style.measurementFigureWidth = style.figureWidth", ...
    "style.visibilityFigureWidth = style.figureWidth", ...
    "style.monteCarloFigureWidth = style.figureWidth", ...
    "style.fitMarginFraction = 0.05", ...
    "style.fitShrinkFactor = 0.97", ...
    "style.fitMinimumAxesScale = 0.50", ...
    "style.fitMaxIterations = 36", ...
    "style.metricPlotPosition = [0.15 0.18 0.70 0.53]", ...
    "style.legend2DGap = 0.08", ...
    "style.geometryPlotPosition = [0.12 0.15 0.76 0.66]", ...
    "style.geometryGridPlotPosition = [0.11 0.12 0.78 0.78]", ...
    "style.geometryLegendGap = -0.04", ...
    "style.geometryXPadding = 0.04", ...
    "style.geometryYPadding = 0.05", ...
    "style.geometryZPadding = 0.05", ...
    "style.groupedBarWidth = 0.64", ...
    "style.categoryLabelAngle = 30"];
assert_tokens(styleText,requiredStyle,'Shared manuscript style');

% The shared 2-D inner plot box must remain centered with protected margins.
assert(contains(styleText,'style.metricPlotPosition = [0.15 0.18 0.70 0.53]'), ...
    '2-D manuscript axes must use balanced protected margins.');

% Every compatibility size alias must resolve to the one standard canvas.
for token = [ ...
        "style.metricFigureHeight = style.figureHeight", ...
        "style.convergenceFigureHeight = style.figureHeight", ...
        "style.geometryFigureHeight = style.figureHeight", ...
        "style.orbitFamilyFigureHeight = style.figureHeight", ...
        "style.slotPhaseFigureHeight = style.figureHeight", ...
        "style.visibilityFigureHeight = style.figureHeight", ...
        "style.measurementFigureHeight = style.figureHeight", ...
        "style.monteCarloFigureHeight = style.figureHeight"]
    assert(contains(styleText,token),'Nonstandard manuscript canvas alias: %s',token);
end

% RA and Dec remain matched.
assert(count(studyText,'style.measurementFigureWidth,style.measurementFigureHeight') >= 2, ...
    'RA/Dec figures must use the same outer manuscript canvas.');
assert(count(studyText,"Position',[0.10,0.12,0.82,0.80]") >= 2, ...
    'RA/Dec figures must use the same axes rectangle.');
assert(count(studyText,'xlim(ax1,[-0.95,5.10])') == 1 && ...
    count(studyText,'xlim(ax2,[-0.95,5.10])') == 1 && ...
    count(studyText,'ylim(ax1,[-0.80,4.20])') == 1 && ...
    count(studyText,'ylim(ax2,[-0.80,4.20])') == 1, ...
    'RA/Dec figures must use matched plotting limits.');

% Every manuscript EPS export is finalized before the proven painters writer.
assert(contains(studyText,'finalize_manuscript_figure(fig);'), ...
    'Study-definition figures must use the shared finalizer.');
assert(contains(curatedText,'finalize_manuscript_figure(fig);'), ...
    'Result figures must use the shared finalizer.');
assert(contains(studyText,"'-depsc2','-painters','-r600','-loose'"), ...
    'Study-definition EPS export path changed unexpectedly.');
assert(contains(curatedText,"'-depsc2','-painters','-r600','-loose'"), ...
    'Result EPS export path changed unexpectedly.');
assert(contains(finalizerText,'style.geometryFontSize') && ...
    contains(finalizerText,'style.geometryLabelFontSize') && ...
    contains(centerText,'style.fitMarginFraction') && ...
    contains(centerText,'style.fitShrinkFactor') && ...
    contains(centerText,'enforce_safe_bounds') && ...
    contains(centerText,'safe = [marginX,fw-marginX,marginY,fh-marginY]'), ...
    'Shared final typography and bounds-safe fit-to-canvas pipeline is incomplete.');

% Legends use the shared two-row policy: 4 entries -> 2 columns and 8 -> 4.
assert(contains(legendColumnsText,'nCols = ceil(nItems/2)') && ...
    contains(legendColumnsText,'nItems == 2') && ...
    contains(legendText,'manuscript_legend_columns(labels,style)') && ...
    contains(finalizerText,'manuscript_legend_columns(lgd,style)'), ...
    'Shared two-row manuscript legend layout is incomplete.');
assert(contains(parallelText,'style.figureWidth style.figureHeight') && ...
    contains(parallelText,'format_manuscript_legend'), ...
    'Parallel figures must use the common canvas and legend formatter.');
assert(contains(styleText,'style.sharedLegendFontSize = 22') && ...
    contains(styleText,'style.sharedGeometryLegendWidth = 3.10') && ...
    contains(geometryGridText,'publication_figure(style.sharedGeometryLegendWidth,style.sharedGeometryLegendHeight)') && ...
    contains(runnerText,'SharedLegendStem'), ...
    'Dense manuscript grids must export compact, readable shared legend strips.');

% Every optimizer-comparison metric uses its matched GA baseline reference.
assert(contains(curatedText,'metricRefs = matched_baselines(baselineResults,missions,3,1, ...') && ...
    contains(curatedText,'style,metricRefs)') && ...
    count(curatedText,'GA baseline') >= 2, ...
    'Comparison metrics must include the matched GA baseline with consistent labeling.');

% Selected equal-time slots must remain visible in vector EPS exports without
% relying on filled marker faces.
assert(count(studyText,"'MarkerSize',13,'MarkerFaceColor','w'") >= 2 && ...
    contains(studyText,"'MarkerEdgeColor',selectedColor,'LineWidth',2.8") && ...
    contains(studyText,"'MarkerEdgeColor',nextColor,'LineWidth',2.8"), ...
    'Equal-time Slot j / Slot j+1 markers must use large EPS-safe outlines.');

assert(contains(tickText,'keep = [1 3]') && ...
    contains(tickText,'span <= 0.15') && ...
    contains(tickText,'keep = [1 numel(ticks)]'), ...
    '3-D tick formatter must remove central zero and thin crowded small-range axes.');
assert(contains(curatedText,'withinGroupSpacing = 1.90') && ...
    contains(curatedText,'caseGap = 2.80') && ...
    contains(curatedText,'tickRotation = 45') && ...
    contains(curatedText,'caseLabels = ["LG","LT","GI"]') && ...
    contains(curatedText,'text(ax,centers(m),108,char(caseLabels(m))'), ...
    'Dense family-comparison labels must use explicit LG/LT/GI abbreviations and non-overlapping optimizer spacing.');
assert(contains(barText,'p(2) = p(2) + 0.02*yRange'), ...
    'LG/LT/GI family-group labels must move slightly upward.');
assert(contains(wrapText,'maxChars = 32') && ...
    contains(wrapText,'abbreviate_manuscript_text'), ...
    'Duration labels must abbreviate before wrapping to avoid EPS cutoff.');
assert(contains(abbrevText,'Effective position sigma (km)') && ...
    contains(abbrevText,'Position RMSE (km)'), ...
    'Long metric labels must be shortened before layout.');

% One root-level entry point produces figures and the LaTeX table printout.
assert(contains(runnerText,'print_manuscript_tables') && ...
    contains(runnerText,'plot_study_definition_figures_for_manuscript') && ...
    contains(runnerText,'make_reviewer2_final_figures'), ...
    'run_manuscript_figures must consolidate definition, result, and table generation.');
assert(contains(tableText,'manuscript_tables.tex') && ...
    contains(tableText,'manuscript_tables.txt'), ...
    'Table printer must save copyable LaTeX and text output.');

fprintf('Reviewer 2 manuscript figure configuration passed.\n');
end

function assert_tokens(textValue,tokens,label)
for token = tokens
    assert(contains(textValue,token), ...
        '%s is missing required token: %s',label,token);
end
end
