function test_fe_study_configuration()
%TEST_FE_STUDY_CONFIGURATION Audit the manuscript FE study entry points.

    projectDir = fileparts(fileparts(mfilename('fullpath')));
    runText = string(fileread(fullfile(projectDir,'run_opt.m')));
    guiText = string(fileread(fullfile(projectDir,'launch_optimization_gui.m')));
    baselineText = string(fileread(fullfile( ...
        projectDir,'scripts','batch','run_baseline_soo.ps1')));
    comparisonText = string(fileread(fullfile( ...
        projectDir,'scripts','batch','run_comparison_soo.ps1')));
    saveText = string(fileread(fullfile( ...
        projectDir,'scripts','save_tracking_results.m')));
    processText = string(fileread(fullfile( ...
        projectDir,'scripts','process_fe_convergence.m')));
    pipelinePilotText = string(fileread(fullfile( ...
        projectDir,'scripts','run_reviewer2_pipeline_pilot.m')));

    assert(~contains(runText,"MAX_ITERS") && ~contains(guiText,"MAX_ITERS") && ...
        ~contains(baselineText,"MAX_ITERS") && ...
        ~contains(comparisonText,"MAX_ITERS"), ...
        'The FE workflow must not expose an iteration fallback.');

    supported = ["GA","PSO","BAYESIAN","ABC","ACO"];
    for optimizer = supported
        doubleQuoted = string(sprintf('"%s"',optimizer));
        singleQuoted = string(sprintf('''%s''',optimizer));
        assert(contains(runText,doubleQuoted) || ...
            contains(runText,singleQuoted), ...
            'run_opt is missing optimizer %s.',optimizer);
        assert(contains(comparisonText,doubleQuoted), ...
            'Comparison batch is missing optimizer %s.',optimizer);
    end
    assert(~contains(runText,"GAMULTIOBJ") && ~contains(runText,"DMOPSO") && ...
        ~contains(guiText,"GAMULTIOBJ") && ~contains(guiText,"DMOPSO"), ...
        'Obsolete multiobjective optimizer branches remain.');

    requiredMissions = [ ...
        "LUNAR_GATEWAY","LOW_THRUST_TRANSFER","GATEWAY_IMPULSE"];
    for mission = requiredMissions
        doubleQuoted = string(sprintf('"%s"',mission));
        assert(contains(runText,doubleQuoted), ...
            'run_opt is missing mission %s.',mission);
        assert(contains(baselineText,doubleQuoted) && ...
            contains(comparisonText,doubleQuoted), ...
            'Batch studies are missing mission %s.',mission);
    end

    requiredCommon = [ ...
        '$env:MAX_EVALS', ...
        '$env:MEAS_NOISE_SEED', ...
        '$env:MAKE_PLOTS = "0"', ...
        '$env:IMPULSE_DV_MPS = "10"', ...
        '$env:IMPULSE_DURATION_TU = "1.5"'];
    for token = requiredCommon
        assert(contains(baselineText,token) && ...
            contains(comparisonText,token), ...
            'Batch studies are missing required setting: %s',token);
    end

    assert(contains(baselineText,'reviewer2_baseline_v1') && ...
        contains(comparisonText,'reviewer2_comparison_v1'), ...
        'Study IDs are missing or not separated.');
    assert(contains(baselineText,'[int[]]$Seeds = (0..19)') && ...
        contains(comparisonText,'[int[]]$Seeds = (0..19)'), ...
        'Default independent-run seed set must be 0:19.');
    assert(contains(comparisonText, ...
        '$MeasurementModels = @("ANGLES_ONLY")') && ...
        contains(comparisonText,'$ObserverCounts = @(3)'), ...
        'Reviewer comparison is not the focused representative design.');

    assert(contains(baselineText,'[switch]$Pilot') && ...
        contains(comparisonText,'[switch]$Pilot') && ...
        contains(baselineText,'BASELINE_PILOT') && ...
        contains(comparisonText,'COMPARISON_PILOT'), ...
        'Small pilot modes are missing from the batch studies.');
    assert(contains(baselineText,'$env:USE_PARALLEL_OPT = "1"') && ...
        contains(comparisonText,'$env:USE_PARALLEL_OPT = "1"'), ...
        'Pilot and full studies must exercise parallel optimization.');

    % Completed deterministic run folders must be skipped on relaunch. Any
    % partial run is preserved outside the study root and rerun cleanly so a
    % week-long study can resume after a MATLAB, Windows, or power failure.
    resumeTokens = [ ...
        '$hasState -and $hasTracking', ...
        '_INCOMPLETE_RUNS', ...
        'Move-Item -Path $RunDir -Destination $archiveDir', ...
        'Skipping completed run'];
    for token = resumeTokens
        assert(contains(baselineText,token) && ...
            contains(comparisonText,token), ...
            'Batch study crash-resume behavior is missing: %s',token);
    end

    % Parallel bayesopt can finish work already in flight after the nominal
    % FE boundary. The comparison must keep BO parallel while admitting only
    % the prescribed FE count and timing the run at that same boundary.
    assert(contains(runText,'parallel_overflow_truncate_v1') && ...
        contains(runText,'bo_outfun') && ...
        contains(runText,'OPT_BO_BUDGET_RUNTIME') && ...
        contains(runText,'ObjectiveTrace(1:FE_BUDGET)') && ...
        contains(runText,'XTrace(1:FE_BUDGET,:)') && ...
        contains(runText,'parallelOverflowEvaluations') && ...
        contains(runText,'budgetRuntime_s') && ...
        contains(runText,'solverWallRuntime_s'), ...
        'Parallel Bayesian FE truncation or budget timing is missing.');
    assert(contains(processText,'parallelOverflowEvaluations') && ...
        contains(processText,'budgetRuntime_s') && ...
        contains(processText,'solverWallRuntime_s') && ...
        contains(processText,'opt == "BAYESIAN"'), ...
        'FE processing does not validate parallel Bayesian overflow metadata.');

    assert(contains(baselineText,'Write-Progress') && ...
        contains(comparisonText,'Write-Progress'), ...
        'Batch studies must show completed-run progress.');
    assert(contains(guiText,'ScreenSize') && ...
        contains(guiText,'gaugeFE'), ...
        'The launcher must use a screen-aware layout and FE progress gauge.');
    assert(~contains(guiText,'Mean det(P_pos)') && ...
        ~contains(saveText,'mean_detPpos_km6'), ...
        'The legacy mean determinant result must not be stored or displayed.');

    assert(contains(pipelinePilotText,'budget = 120') && ...
        contains(pipelinePilotText,'seeds = 0:2') && ...
        contains(pipelinePilotText,'Expected optimization runs: %d') && ...
        contains(pipelinePilotText,'process_fe_convergence') && ...
        contains(pipelinePilotText,'-ExecutionPolicy Bypass') && ...
        contains(pipelinePilotText,'select_best_observed_runs') && ...
        contains(pipelinePilotText,'plot_best_trajectory') && ...
        contains(pipelinePilotText,'plot_best_ekf_errors') && ...
        contains(pipelinePilotText,'availableObsCount'), ...
        'The end-to-end three-seed pipeline pilot is incomplete.');
    for optimizer = supported
        assert(contains(pipelinePilotText,optimizer), ...
            'Pipeline pilot is missing optimizer %s.',optimizer);
    end
    for mission = requiredMissions
        assert(contains(pipelinePilotText,mission), ...
            'Pipeline pilot is missing mission %s.',mission);
    end

    fprintf('FE study configuration passed.\n');
end
