function test_fe_study_configuration()
%TEST_FE_STUDY_CONFIGURATION Audit the manuscript FE study entry points.

    projectDir = fileparts(fileparts(mfilename('fullpath')));
    runText = string(fileread(fullfile(projectDir,'run_opt.m')));
    guiText = string(fileread(fullfile(projectDir,'launch_optimization_gui.m')));
    baselineText = string(fileread(fullfile( ...
        projectDir,'scripts','batch','run_baseline_soo.ps1')));
    comparisonText = string(fileread(fullfile( ...
        projectDir,'scripts','batch','run_comparison_soo.ps1')));
    bayesianStudyText = string(fileread(fullfile( ...
        projectDir,'scripts','batch','run_bayesian_1200_soo.ps1')));
    saveText = string(fileread(fullfile( ...
        projectDir,'scripts','save_tracking_results.m')));
    processText = string(fileread(fullfile( ...
        projectDir,'scripts','process_fe_convergence.m')));
    pipelinePilotText = string(fileread(fullfile( ...
        projectDir,'scripts','run_reviewer2_pipeline_pilot.m')));
    trajectoryPlotText = string(fileread(fullfile( ...
        projectDir,'scripts','plot_reviewer2_best_trajectories.m')));
    studyFigureText = string(fileread(fullfile( ...
        projectDir,'scripts','plot_study_definition_figures.m')));

    assert(~contains(runText,"MAX_ITERS") && ~contains(guiText,"MAX_ITERS") && ...
        ~contains(baselineText,"MAX_ITERS") && ...
        ~contains(comparisonText,"MAX_ITERS") && ...
        ~contains(bayesianStudyText,"MAX_ITERS"), ...
        'The FE workflow must not expose an iteration fallback.');

    supported = ["GA","PSO","BAYESIAN","ABC","ACO"];
    for optimizer = supported
        doubleQuoted = string(sprintf('"%s"',optimizer));
        singleQuoted = string(sprintf('''%s''',optimizer));
        assert(contains(runText,doubleQuoted) || ...
            contains(runText,singleQuoted), ...
            'run_opt is missing optimizer %s.',optimizer);
    end
    assert(contains(comparisonText, ...
        '$Algs = @("GA", "PSO", "ABC", "ACO")'), ...
        'The full 6000-FE comparison must exclude Bayesian optimization.');
    assert(contains(comparisonText, ...
        '$Algs = @("GA", "PSO", "BAYESIAN", "ABC", "ACO")'), ...
        'The existing 1200-FE dress rehearsal must retain all five methods.');
    assert(~contains(runText,"GAMULTIOBJ") && ~contains(runText,"DMOPSO") && ...
        ~contains(guiText,"GAMULTIOBJ") && ~contains(guiText,"DMOPSO"), ...
        'Obsolete multiobjective optimizer branches remain.');

    requiredMissions = [ ...
        "LUNAR_GATEWAY","LOW_THRUST_TRANSFER","GATEWAY_IMPULSE"];
    for mission = requiredMissions
        doubleQuoted = string(sprintf('"%s"',mission));
        assert(contains(runText,doubleQuoted), ...
            'run_opt is missing mission %s.',mission);
        assert(contains(baselineText,doubleQuoted) && ...
            contains(comparisonText,doubleQuoted), ...
            'Batch studies are missing mission %s.',mission);
    end

    requiredCommon = [ ...
        '$env:MAX_EVALS', ...
        '$env:MEAS_NOISE_SEED', ...
        '$env:MAKE_PLOTS = "0"', ...
        '$env:IMPULSE_DV_MPS = "10"', ...
        '$env:IMPULSE_DURATION_TU = "1.5"'];
    for token = requiredCommon
        assert(contains(baselineText,token) && ...
            contains(comparisonText,token) && ...
            contains(bayesianStudyText,token), ...
            'Batch studies are missing required setting: %s',token);
    end

    assert(contains(baselineText,'reviewer2_baseline_v1') && ...
        contains(comparisonText,'reviewer2_comparison_v1') && ...
        contains(bayesianStudyText,'reviewer2_bayesian_1200_v1'), ...
        'Study IDs are missing or not separated.');
    assert(contains(baselineText,'[int[]]$Seeds = (0..19)') && ...
        contains(comparisonText,'[int[]]$Seeds = (0..19)') && ...
        contains(bayesianStudyText,'[int[]]$Seeds = (0..19)'), ...
        'Default independent-run seed set must be 0:19.');
    assert(contains(comparisonText, ...
        '$MeasurementModels = @("ANGLES_ONLY")') && ...
        contains(comparisonText,'$ObserverCounts = @(3)'), ...
        'Reviewer comparison is not the focused representative design.');
    assert(contains(bayesianStudyText,'$Alg = "BAYESIAN"') && ...
        contains(bayesianStudyText,'$EvalBudget = 1200') && ...
        contains(bayesianStudyText,'$MissionType = "LUNAR_GATEWAY"') && ...
        contains(bayesianStudyText,'$MeasModel = "ANGLES_ONLY"') && ...
        contains(bayesianStudyText,'$NumObservers = 3') && ...
        contains(bayesianStudyText,'$NPeriods = 1') && ...
        contains(bayesianStudyText,'$StudyFolder = "BAYESIAN_1200"'), ...
        'The dedicated Bayesian study is not the focused 1200-FE LG design.');

    assert(contains(baselineText,'[switch]$Pilot') && ...
        contains(comparisonText,'[switch]$Pilot') && ...
        contains(baselineText,'BASELINE_PILOT') && ...
        contains(comparisonText,'COMPARISON_PILOT_1200') && ...
        contains(comparisonText,'$EvalBudget = 1200') && ...
        contains(comparisonText,'reviewer2_comparison_pilot_1200_v1'), ...
        'Comparison pilot must use the isolated 1200-FE dress rehearsal.');
    assert(contains(baselineText,'$env:USE_PARALLEL_OPT = "1"') && ...
        contains(comparisonText,'$env:USE_PARALLEL_OPT = "1"') && ...
        contains(bayesianStudyText,'$env:USE_PARALLEL_OPT = "1"'), ...
        'Pilot and full studies must exercise parallel optimization.');

    % Completed deterministic run folders must be skipped on relaunch. Any
    % partial run is preserved outside the study root and rerun cleanly so a
    % long study can resume after a MATLAB, Windows, or power failure.
    resumeTokens = [ ...
        '$hasState -and $hasTracking', ...
        '_INCOMPLETE_RUNS', ...
        'Move-Item -Path $RunDir -Destination $archiveDir', ...
        'Skipping completed run'];
    for token = resumeTokens
        assert(contains(baselineText,token) && ...
            contains(comparisonText,token) && ...
            contains(bayesianStudyText,token), ...
            'Batch study crash-resume behavior is missing: %s',token);
    end

    % Parallel bayesopt can finish work already in flight after the nominal
    % FE boundary. Keep BO parallel while admitting only the prescribed FE
    % count and timing the run at that same boundary.
    assert(contains(runText,'parallel_overflow_truncate_v1') && ...
        contains(runText,'bo_outfun') && ...
        contains(runText,'OPT_BO_BUDGET_RUNTIME') && ...
        contains(runText,'ObjectiveTrace(1:FE_BUDGET)') && ...
        contains(runText,'XTrace(1:FE_BUDGET,:)') && ...
        contains(runText,'parallelOverflowEvaluations') && ...
        contains(runText,'budgetRuntime_s') && ...
        contains(runText,'solverWallRuntime_s'), ...
        'Parallel Bayesian FE truncation or budget timing is missing.');
    assert(contains(processText,'parallelOverflowEvaluations') && ...
        contains(processText,'budgetRuntime_s') && ...
        contains(processText,'solverWallRuntime_s') && ...
        contains(processText,'opt == "BAYESIAN"'), ...
        'FE processing does not validate parallel Bayesian overflow metadata.');

    assert(contains(baselineText,'Write-Progress') && ...
        contains(comparisonText,'Write-Progress') && ...
        contains(bayesianStudyText,'Write-Progress'), ...
        'Batch studies must show completed-run progress.');
    assert(contains(guiText,'ScreenSize') && ...
        contains(guiText,'gaugeFE'), ...
        'The launcher must use a screen-aware layout and FE progress gauge.');
    assert(~contains(guiText,'Mean det(P_pos)') && ...
        ~contains(saveText,'mean_detPpos_km6'), ...
        'The legacy mean determinant result must not be stored or displayed.');

    assert(contains(pipelinePilotText,'budget = 1200') && ...
        contains(pipelinePilotText,'seeds = 0:2') && ...
        contains(pipelinePilotText,'COMPARISON_PILOT_1200') && ...
        contains(pipelinePilotText,'reviewer2_comparison_pilot_1200_v1') && ...
        contains(pipelinePilotText,'Expected optimization runs: %d') && ...
        contains(pipelinePilotText,'process_fe_convergence') && ...
        contains(pipelinePilotText,'plot_reviewer2_full_fe_convergence') && ...
        contains(pipelinePilotText,'-ExecutionPolicy Bypass') && ...
        contains(pipelinePilotText,'select_best_observed_runs') && ...
        contains(pipelinePilotText, ...
            'plot_reviewer2_best_trajectories(analysisDir,saveFigures,bestRuns)') && ...
        contains(pipelinePilotText,'plot_best_run_ekf_errors') && ...
        contains(pipelinePilotText,'plot_best_ekf_errors') && ...
        contains(pipelinePilotText,'availableObsCount'), ...
        'The end-to-end three-seed 1200-FE pipeline pilot is incomplete.');
    assert(contains(trajectoryPlotText, ...
        'plotPosition = [0.12 0.20 0.76 0.64]') && ...
        contains(trajectoryPlotText,'view(ax,-37.5,30)') && ...
        contains(trajectoryPlotText,'legendGap = 0.012') && ...
        contains(trajectoryPlotText,'lgd.Position = legendPosition') && ...
        contains(trajectoryPlotText,'standardize_best_run_table') && ...
        contains(trajectoryPlotText,'final_run_metrics.csv'), ...
        ['The trajectory exporter must accept the in-memory best-run table ' ...
         'and recover older CSV path fields.']);
    assert(contains(studyFigureText, ...
        'plotPosition = [0.12 0.20 0.76 0.64]') && ...
        contains(studyFigureText,'legendGap = 0.012') && ...
        contains(studyFigureText,'finalize_centered_3d_axes') && ...
        contains(studyFigureText,'draw_leader_arrow') && ...
        contains(studyFigureText,'patch(ax,headX,headY,lineColor') && ...
        contains(studyFigureText,'Draw after the white text box') && ...
        contains(studyFigureText,'''MarkerSize'',3') && ...
        contains(studyFigureText,'ax.XTick = xTicks([1,end])') && ...
        contains(studyFigureText,'occLeaderPoint') && ...
        contains(studyFigureText,'rhoXYLabelY') && ...
        contains(studyFigureText,'rhoLabelY') && ...
        contains(studyFigureText,'0.5*thetaKeepout'), ...
        ['Study-definition 3-D figures or visibility/DRO annotations ' ...
         'are not using the manuscript-wide layout.']);
    assert(~contains(pipelinePilotText,'function fig = plot_best_trajectory'), ...
        'The pipeline still contains a duplicate trajectory renderer.');
    for optimizer = supported
        assert(contains(pipelinePilotText,optimizer), ...
            'Pipeline pilot is missing optimizer %s.',optimizer);
    end
    for mission = requiredMissions
        assert(contains(pipelinePilotText,mission), ...
            'Pipeline pilot is missing mission %s.',mission);
    end

    fprintf('FE study configuration passed.\n');
end
