function test_baseline_pipeline_configuration()
%TEST_BASELINE_PIPELINE_CONFIGURATION Audit completed baseline processing.

projectDir = fileparts(fileparts(mfilename('fullpath')));
pipelineText = string(fileread(fullfile( ...
    projectDir,'scripts','run_reviewer2_baseline_pipeline.m')));
launcherText = string(fileread(fullfile( ...
    projectDir,'scripts','batch','run_baseline_soo.ps1')));
geometryText = string(fileread(fullfile( ...
    projectDir,'scripts','plot_reviewer2_constellation_geometry.m')));

requiredPipeline = string({ ...
    'budget = 6000', ...
    'plotStartFE = 60', ...
    'seeds = 0:19', ...
    'measurements = ["ANGLES_ONLY","ANGLES_RANGE"]', ...
    'missions = ["LUNAR_GATEWAY","LOW_THRUST_TRANSFER","GATEWAY_IMPULSE"]', ...
    'observerCounts = [3 5 7 10]', ...
    'gatewayPeriods = [1 3 5]', ...
    'studyID = "reviewer2_baseline_v1"', ...
    'baselineRoot = fullfile(paths.runs,''BASELINE'')', ...
    'expectedGroups = 2*(4*3 + 4 + 4)', ...
    'expectedRuns = expectedGroups*numel(seeds)', ...
    'expectedConvergenceFigures = numel(missions)*numel(measurements) + numel(measurements)', ...
    'process_fe_convergence', ...
    'validate_baseline_factorial', ...
    'select_baseline_geometry_runs', ...
    'results.Measurement == "ANGLES_ONLY"', ...
    'results.NPeriods == 1', ...
    'plot_observer_count_convergence', ...
    'plot_gateway_period_convergence', ...
    'load_ga_curve', ...
    'baseline_convergence_vs_observers_', ...
    'baseline_convergence_vs_periods_', ...
    'plot_observer_count_metric', ...
    'plot_gateway_period_metric', ...
    'plot_reviewer2_constellation_geometry', ...
    'baseline_6000_results.csv', ...
    'baseline_6000_geometry_selected_runs.csv', ...
    'baseline_6000_geometry_details.csv'});
for token = requiredPipeline
    assert(contains(pipelineText,token), ...
        'Baseline processing pipeline is missing required token: %s',token);
end

requiredLauncher = string({ ...
    '$StudyId = "reviewer2_baseline_v1"', ...
    '$MeasurementModels = @("ANGLES_ONLY", "ANGLES_RANGE")', ...
    '$ObserverCounts = @(3, 5, 7, 10)', ...
    '$GatewayPeriods = @(1, 3, 5)', ...
    '$env:USE_SCREENING = "1"', ...
    '$env:USE_J1 = "1"', ...
    '$env:USE_J2 = "1"', ...
    '$env:USE_J3 = "1"'});
for token = requiredLauncher
    assert(contains(launcherText,token), ...
        'Baseline launcher is missing required token: %s',token);
end

% Validate behavior rather than depending on one exact wrapped comment.
requiredGeometry = string({ ...
    'period = double(observers.period_TU(j))', ...
    'tPlot = linspace(0,period,300)', ...
    'cr3bp_dynamics', ...
    'reviewer2_target_color', ...
    '''Target trajectory''', ...
    '''Observer orbits''', ...
    'OrbitFamilies', ...
    'OrbitIndices', ...
    'SlotIndices'});
for token = requiredGeometry
    assert(contains(geometryText,token), ...
        'Shared constellation geometry exporter is missing required behavior: %s',token);
end

assert(~contains(geometryText,'earthCenter') && ...
    ~contains(geometryText,'earthRadius') && ...
    ~contains(geometryText,'''Earth'''), ...
    'Earth must be omitted from lunar-region baseline geometry plots.');

% Baseline definition: AO/AR x [(4 observer counts x 3 LG periods)
% + 4 LT counts + 4 impulse counts] x 20 seeds = 800 runs.
assert(2*(4*3+4+4)*20 == 800);
assert(3*2 + 2 == 8,'Baseline convergence layout must contain 8 figures.');

fprintf('Baseline pipeline configuration passed.\n');
end
