function test_ga_objective_screening_configuration()
%TEST_GA_OBJECTIVE_SCREENING_CONFIGURATION Audit the GA sensitivity study.

projectDir = fileparts(fileparts(mfilename('fullpath')));
studyRaw = fileread(fullfile( ...
    projectDir,'scripts','batch','run_ga_objective_screening_soo.ps1'));
studyText = string(studyRaw);
processorText = string(fileread(fullfile( ...
    projectDir,'scripts','run_reviewer2_objective_screening_pipeline.m')));

requiredCommon = string({ ...
    '$StudyId = "reviewer2_ga_objective_screening_v1"', ...
    '$StudyFolder = "GA_OBJECTIVE_SCREENING"', ...
    '[int]$EvalBudget = 6000', ...
    '[int[]]$Seeds = (0..19)', ...
    '$env:OPTIMIZER_MODE = "GA"', ...
    '$env:USE_PARALLEL_OPT = "1"', ...
    '$env:MEAS_MODEL = "ANGLES_ONLY"', ...
    '$env:NUM_OBSERVERS = "3"', ...
    '$env:NPERIODS = "1"', ...
    '$env:MEAS_NOISE_SEED = "$MeasurementNoiseSeed"', ...
    '$MeasurementNoiseSeed = 1001', ...
    '$MissionTypes = @("LUNAR_GATEWAY", "LOW_THRUST_TRANSFER", "GATEWAY_IMPULSE")', ...
    '$TotalRuns = $Cases.Count * $MissionTypes.Count * $Seeds.Count', ...
    '_INCOMPLETE_RUNS', ...
    'Skipping completed run'});

for token = requiredCommon
    assert(contains(studyText,token), ...
        'GA objective/screening study is missing required token: %s',token);
end

% Match the five rows of the original comparison-study configuration table.
caseCodes = ["combined_on","combined_off","j1_only","j2_only","j3_only"];
caseLabels = [ ...
    "Combined objective with screening", ...
    "Combined objective without screening", ...
    "Estimation-error only", ...
    "Uncertainty only", ...
    "Stability only"];
expected = [ ...
    1 1 1 1; ... % screening, J1, J2, J3
    0 1 1 1; ...
    1 1 0 0; ...
    1 0 1 0; ...
    1 0 0 1];

starts = zeros(size(caseCodes));
for k = 1:numel(caseCodes)
    marker = sprintf('Code = "%s"',char(caseCodes(k)));
    idx = strfind(studyRaw,marker);
    assert(numel(idx) == 1, ...
        'Expected exactly one GA sensitivity case block for %s.',caseCodes(k));
    starts(k) = idx;
end
assert(all(diff(starts) > 0), ...
    'GA sensitivity cases are missing or out of the expected table order.');

for k = 1:numel(caseCodes)
    if k < numel(caseCodes)
        blockRaw = studyRaw(starts(k):starts(k+1)-1);
    else
        blockRaw = studyRaw(starts(k):end);
    end
    block = string(blockRaw);

    labelToken = string(sprintf('Label = "%s"',char(caseLabels(k))));
    assert(contains(block,labelToken), ...
        'GA sensitivity case %s has the wrong label.',caseCodes(k));

    names = ["Screening","J1","J2","J3"];
    for j = 1:numel(names)
        switchToken = string(sprintf('%s = %d',char(names(j)),expected(k,j)));
        assert(contains(block,switchToken), ...
            'GA sensitivity case %s has the wrong %s switch.', ...
            caseCodes(k),names(j));
    end
end

% Only the combined-objective OFF case should disable screening.
assert(count(studyText,"Screening = 0") == 1, ...
    'Exactly one study configuration should disable screening.');

% Full study: 5 cases x 3 missions x 20 seeds = 300 optimization runs.
assert(5*3*20 == 300);

requiredProcessor = string({ ...
    'studyID = "reviewer2_ga_objective_screening_v1"', ...
    'root = fullfile(paths.runs,''GA_OBJECTIVE_SCREENING'')', ...
    'process_fe_convergence', ...
    'Total objective values are compared only for combined_on/combined_off', ...
    'ga_screening_contrasts.csv', ...
    'ga_objective_component_winners.csv', ...
    'ga_objective_family_selection.csv', ...
    'plot_screening_convergence', ...
    'plot_component_metrics', ...
    'plot_family_selection'});
for token = requiredProcessor
    assert(contains(processorText,token), ...
        'GA objective/screening processor is missing required token: %s',token);
end

fprintf('GA objective/screening study configuration passed.\n');
end
