function test_manuscript_consolidated_figures()
%TEST_MANUSCRIPT_CONSOLIDATED_FIGURES Audit the shared manuscript figure folder.

projectDir = fileparts(fileparts(mfilename('fullpath')));
runnerText = string(fileread(fullfile(projectDir,'run_manuscript_figures.m')));

required = [ ...
    "output.figureDirectory = string(fullfile(output.directory,'figures'))", ...
    "destinationEps = fullfile(output.figureDirectory,stem+\".eps\")", ...
    "destinationPng = fullfile(output.figureDirectory,stem+\".png\")", ...
    "'ConsolidatedEPS'", ...
    "print_manuscript_tables('OutputDirectory',output.directory)"];

for token = required
    assert(contains(runnerText,token), ...
        'Manuscript runner is missing consolidated-output token: %s',token);
end

assert(contains(runnerText,'for pattern = ["*.eps","*.png"]'), ...
    'ClearDirectory must clear stale consolidated figure exports.');
assert(contains(runnerText,'copyfile(sources(k),destinationEps,''f'')'), ...
    'EPS files must be copied into the consolidated figure directory.');

fprintf('Manuscript consolidated figure-folder configuration passed.\n');
end
