function test_ga_objective_screening_configuration()
%TEST_GA_OBJECTIVE_SCREENING_CONFIGURATION Audit the GA sensitivity study.

projectDir = fileparts(fileparts(mfilename('fullpath')));
studyRaw = fileread(fullfile( ...
    projectDir,'scripts','batch','run_ga_objective_screening_soo.ps1'));
studyText = string(studyRaw);

requiredCommon = string({ ...
    '$StudyId = "reviewer2_ga_objective_screening_v1"', ...
    '$StudyFolder = "GA_OBJECTIVE_SCREENING"', ...
    '[int]$EvalBudget = 6000', ...
    '[int[]]$Seeds = (0..19)', ...
    '$env:OPTIMIZER_MODE = "GA"', ...
    '$env:USE_PARALLEL_OPT = "1"', ...
    '$env:MEAS_MODEL = "ANGLES_ONLY"', ...
    '$env:NUM_OBSERVERS = "3"', ...
    '$env:NPERIODS = "1"', ...
    '$env:MEAS_NOISE_SEED = "$MeasurementNoiseSeed"', ...
    '$MeasurementNoiseSeed = 1001', ...
    '$MissionTypes = @("LUNAR_GATEWAY", "LOW_THRUST_TRANSFER", "GATEWAY_IMPULSE")', ...
    '$TotalRuns = $Cases.Count * $MissionTypes.Count * $Seeds.Count', ...
    '_INCOMPLETE_RUNS', ...
    'Skipping completed run'});

for token = requiredCommon
    assert(contains(studyText,token), ...
        'GA objective/screening study is missing required token: %s',token);
end

% Match the five rows of the original comparison-study configuration table.
caseCodes = ["combined_on","combined_off","j1_only","j2_only","j3_only"];
caseLabels = [ ...
    "Combined objective with screening", ...
    "Combined objective without screening", ...
    "Estimation-error only", ...
    "Uncertainty only", ...
    "Stability only"];
expected = [ ...
    1 1 1 1; ... % screening, J1, J2, J3
    0 1 1 1; ...
    1 1 0 0; ...
    1 0 1 0; ...
    1 0 0 1];

starts = zeros(size(caseCodes));
for k = 1:numel(caseCodes)
    marker = 'Code = "' + caseCodes(k) + '"';
    idx = strfind(studyRaw,char(marker));
    assert(numel(idx) == 1, ...
        'Expected exactly one GA sensitivity case block for %s.',caseCodes(k));
    starts(k) = idx;
end
assert(all(diff(starts) > 0), ...
    'GA sensitivity cases are missing or out of the expected table order.');

for k = 1:numel(caseCodes)
    if k < numel(caseCodes)
        blockRaw = studyRaw(starts(k):starts(k+1)-1);
    else
        blockRaw = studyRaw(starts(k):end);
    end
    block = string(blockRaw);

    assert(contains(block,'Label = "' + caseLabels(k) + '"'), ...
        'GA sensitivity case %s has the wrong label.',caseCodes(k));
    assert(contains(block,"Screening = " + expected(k,1)), ...
        'GA sensitivity case %s has the wrong screening switch.',caseCodes(k));
    assert(contains(block,"J1 = " + expected(k,2)), ...
        'GA sensitivity case %s has the wrong J1 switch.',caseCodes(k));
    assert(contains(block,"J2 = " + expected(k,3)), ...
        'GA sensitivity case %s has the wrong J2 switch.',caseCodes(k));
    assert(contains(block,"J3 = " + expected(k,4)), ...
        'GA sensitivity case %s has the wrong J3 switch.',caseCodes(k));
end

% Only the combined-objective OFF case should disable screening.
assert(count(studyText,"Screening = 0") == 1, ...
    'Exactly one study configuration should disable screening.');

% Full study: 5 cases x 3 missions x 20 seeds = 300 optimization runs.
assert(5*3*20 == 300);

fprintf('GA objective/screening study configuration passed.\n');
end
