function test_fe_study_configuration()
%TEST_FE_STUDY_CONFIGURATION Audit the manuscript FE study entry points.

    projectDir = fileparts(fileparts(mfilename('fullpath')));
    runText = string(fileread(fullfile(projectDir,'run_opt.m')));
    guiText = string(fileread(fullfile(projectDir,'launch_optimization_gui.m')));
    baselineText = string(fileread(fullfile( ...
        projectDir,'scripts','batch','run_baseline_soo.ps1')));
    comparisonText = string(fileread(fullfile( ...
        projectDir,'scripts','batch','run_comparison_soo.ps1')));
    saveText = string(fileread(fullfile( ...
        projectDir,'scripts','save_tracking_results.m')));

    assert(~contains(runText,"MAX_ITERS") && ~contains(guiText,"MAX_ITERS") && ...
        ~contains(baselineText,"MAX_ITERS") && ...
        ~contains(comparisonText,"MAX_ITERS"), ...
        'The FE workflow must not expose an iteration fallback.');

    supported = ["GA","PSO","BAYESIAN","ABC","ACO"];
    for optimizer = supported
        doubleQuoted = string(sprintf('"%s"',optimizer));
        singleQuoted = string(sprintf('''%s''',optimizer));
        assert(contains(runText,doubleQuoted) || ...
            contains(runText,singleQuoted), ...
            'run_opt is missing optimizer %s.',optimizer);
        assert(contains(comparisonText,doubleQuoted), ...
            'Comparison batch is missing optimizer %s.',optimizer);
    end
    assert(~contains(runText,"GAMULTIOBJ") && ~contains(runText,"DMOPSO") && ...
        ~contains(guiText,"GAMULTIOBJ") && ~contains(guiText,"DMOPSO"), ...
        'Obsolete multiobjective optimizer branches remain.');

    requiredMissions = [ ...
        "LUNAR_GATEWAY","LOW_THRUST_TRANSFER","GATEWAY_IMPULSE"];
    for mission = requiredMissions
        doubleQuoted = string(sprintf('"%s"',mission));
        assert(contains(runText,doubleQuoted), ...
            'run_opt is missing mission %s.',mission);
        assert(contains(baselineText,doubleQuoted) && ...
            contains(comparisonText,doubleQuoted), ...
            'Batch studies are missing mission %s.',mission);
    end

    requiredCommon = [ ...
        '$env:MAX_EVALS', ...
        '$env:MEAS_NOISE_SEED', ...
        '$env:MAKE_PLOTS = "0"', ...
        '$env:IMPULSE_DV_MPS = "10"', ...
        '$env:IMPULSE_DURATION_TU = "1.5"'];
    for token = requiredCommon
        assert(contains(baselineText,token) && ...
            contains(comparisonText,token), ...
            'Batch studies are missing required setting: %s',token);
    end

    assert(contains(baselineText,'reviewer2_baseline_v1') && ...
        contains(comparisonText,'reviewer2_comparison_v1'), ...
        'Study IDs are missing or not separated.');
    assert(contains(baselineText,'[int[]]$Seeds = (0..19)') && ...
        contains(comparisonText,'[int[]]$Seeds = (0..19)'), ...
        'Default independent-run seed set must be 0:19.');
    assert(contains(comparisonText, ...
        '$MeasurementModels = @("ANGLES_ONLY")') && ...
        contains(comparisonText,'$ObserverCounts = @(3)'), ...
        'Reviewer comparison is not the focused representative design.');

    assert(contains(baselineText,'[switch]$Pilot') && ...
        contains(comparisonText,'[switch]$Pilot') && ...
        contains(baselineText,'BASELINE_PILOT') && ...
        contains(comparisonText,'COMPARISON_PILOT'), ...
        'Small pilot modes are missing from the batch studies.');
    assert(contains(baselineText,'Write-Progress') && ...
        contains(comparisonText,'Write-Progress'), ...
        'Batch studies must show completed-run progress.');
    assert(contains(guiText,'ScreenSize') && ...
        contains(guiText,'gaugeFE'), ...
        'The launcher must use a screen-aware layout and FE progress gauge.');
    assert(~contains(guiText,'Mean det(P_pos)') && ...
        ~contains(saveText,'mean_detPpos_km6'), ...
        'The legacy mean determinant result must not be stored or displayed.');

    fprintf('FE study configuration passed.\n');
end
