function test_comparison_pipeline_configuration()
%TEST_COMPARISON_PIPELINE_CONFIGURATION Audit the 6000-FE result processor.

projectDir = fileparts(fileparts(mfilename('fullpath')));
pipelineText = string(fileread(fullfile( ...
    projectDir,'scripts','run_reviewer2_comparison_pipeline.m')));
launcherText = string(fileread(fullfile( ...
    projectDir,'scripts','batch','run_comparison_soo.ps1')));

requiredPipeline = [ ...
    'budget = 6000', ...
    'seeds = 0:19', ...
    'optimizers = ["GA","PSO","ABC","ACO"]', ...
    'missions = ["LUNAR_GATEWAY","LOW_THRUST_TRANSFER","GATEWAY_IMPULSE"]', ...
    'studyID = "reviewer2_comparison_v1"', ...
    'comparisonRoot = fullfile(paths.runs,''COMPARISON'')', ...
    'expectedRuns = numel(optimizers)*numel(missions)*numel(seeds)', ...
    'process_fe_convergence', ...
    'plotStartFE = 60', ...
    'comparison_6000_objective', ...
    'comparison_6000_runtime', ...
    'comparison_6000_position_rmse', ...
    'comparison_6000_effective_sigma', ...
    'comparison_6000_coverage', ...
    'comparison_6000_screening_count', ...
    'comparison_6000_stability', ...
    'build_screening_sensitivity', ...
    'SCREENING_SENSITIVITY_GA_6000', ...
    'evaluate_screening_off', ...
    'runMetrics.optimizer == "GA"', ...
    'cr3bp_ekf', ...
    'earth_exclusion,false,measCfg', ...
    'Screening ON', ...
    'Screening OFF', ...
    'diagnostic EKF re-evaluated with screening OFF'];

for token = requiredPipeline
    assert(contains(pipelineText,token), ...
        'Comparison processing pipeline is missing required token: %s',token);
end

requiredLauncher = [ ...
    '$StudyId = "reviewer2_comparison_v1"', ...
    '$Algs = @("GA", "PSO", "ABC", "ACO")', ...
    '$MeasurementModels = @("ANGLES_ONLY")', ...
    '$MissionTypes = @("LUNAR_GATEWAY", "LOW_THRUST_TRANSFER", "GATEWAY_IMPULSE")', ...
    '$ObserverCounts = @(3)', ...
    '$GatewayPeriods = @(1)', ...
    '$env:USE_SCREENING = "1"'];

for token = requiredLauncher
    assert(contains(launcherText,token), ...
        'Full comparison launcher is missing required token: %s',token);
end

% The screening-OFF result must be a post-optimization diagnostic only. The
% full comparison launcher itself remains screening ON and has no screening
% sweep dimension.
assert(~contains(launcherText,'$ScreeningModes'), ...
    'The completed 6000-FE optimizer study should not be redefined retroactively.');

% Check the scientific interpretation using independent phrases so harmless
% MATLAB comment wrapping cannot cause a false test failure.
assert(contains(pipelineText,'GA designs from each') && ...
    contains(pipelineText,'are held fixed') && ...
    contains(pipelineText,'diagnostic EKF is re-evaluated with') && ...
    contains(pipelineText,'screening OFF') && ...
    contains(pipelineText,'isolates the measurement-availability gate') && ...
    contains(pipelineText,'optimization with screening disabled.'), ...
    'The screening sensitivity interpretation is not documented explicitly.');

fprintf('Comparison pipeline configuration passed.\n');
end
