function test_reviewer2_paper_figures_configuration()
%TEST_REVIEWER2_PAPER_FIGURES_CONFIGURATION Audit final manuscript rendering.

projectDir = fileparts(fileparts(mfilename('fullpath')));
styleText = string(fileread(fullfile(projectDir,'scripts','reviewer2_paper_style.m')));
geometryText = string(fileread(fullfile(projectDir,'scripts','plot_reviewer2_geometry_grid.m')));
selectorText = string(fileread(fullfile(projectDir,'scripts','select_reviewer2_representative_runs.m')));
figureText = string(fileread(fullfile(projectDir,'scripts','make_reviewer2_final_figures.m')));
runnerText = string(fileread(fullfile(projectDir,'scripts','run_reviewer2_results.m')));
introText = string(fileread(fullfile(projectDir,'scripts','plot_study_definition_figures.m')));

requiredStyle = string({ ...
    'style.fontName = ''Times New Roman''', ...
    'style.fontSize = 12', ...
    'style.labelFontSize = 14', ...
    'style.geometryFigureWidth = 7.6', ...
    'style.geometryFigureHeight = 7.0', ...
    'style.geometryPlotPosition = [0.12 0.20 0.76 0.64]', ...
    'style.geometryAzimuth = -37.5', ...
    'style.geometryElevation = 30'});
assert_tokens(styleText,requiredStyle,'Shared paper style');

assert(contains(introText,'publication_figure(7.6,7.0)') && ...
    contains(introText,'plotPosition = [0.12 0.20 0.76 0.64]') && ...
    contains(introText,'view(ax,-37.5,30)'), ...
    'Introductory 3-D reference layout changed unexpectedly.');

requiredSelector = string({ ...
    'closest to the 20-run group mean', ...
    'height(candidates) == 20', ...
    'GroupMeanObjective', ...
    'GroupStdObjective'});
assert_tokens(selectorText,requiredSelector,'Representative geometry selector');
assert(~contains(selectorText,'min(candidates.bestJ)'), ...
    'Geometry must not select the best individual seed.');

requiredGeometry = string({ ...
    '7.6 x 7.0 inch canvas', ...
    'panelCells = cell(n,1)', ...
    'style.geometryPlotPosition', ...
    'PositionConstraint = ''innerposition''', ...
    'center_reference_legend', ...
    'common_geometry_limits', ...
    'panel.uniqueOrbitKeys = unique(panel.orbitKeys,''stable'')', ...
    '''Endpoint orbits''', ...
    'FigureStem'});
assert_tokens(geometryText,requiredGeometry,'Geometry exporter');
assert(~contains(geometryText,'earthCenter') && ~contains(geometryText,'''Earth'''), ...
    'Final geometry figures must omit Earth.');
assert(~contains(geometryText,'''--'''), ...
    'Final result geometry must use solid trajectory/orbit lines.');

% Several final figure stems are intentionally assembled dynamically from a
% metric suffix. Audit the construction and the metric specification lists
% rather than requiring impossible fully expanded source-code literals.
requiredFigures = string({ ...
    'plot_curve_overlay', ...
    'runtime_1200_objective', ...
    'runtime_1200_runtime', ...
    'runtime_1200_convergence', ...
    'comparison_6000_objective', ...
    'comparison_6000_position_rmse', ...
    'comparison_6000_effective_sigma', ...
    'comparison_6000_stability', ...
    'comparison_6000_convergence_', ...
    'observerSpecs = {', ...
    '"baseline_observer_"+string(observerSpecs{q,4})+"_"+mission_code(mission)', ...
    'baseline_convergence_observers_', ...
    'durationSpecs = {', ...
    '"baseline_gateway_duration_"+string(durationSpecs{q,4})', ...
    'baseline_convergence_duration_', ...
    'screeningSpecs = {', ...
    '"ga_screening_"+string(screeningSpecs{q,4})+"_"+mission_code(mission)', ...
    'ga_screening_convergence_', ...
    'componentSpecs = {', ...
    '"ga_objective_"+string(componentSpecs{q,4})+"_"+mission_code(mission)', ...
    '''BestJMean'',''BestJStd'',''Final best objective'',''objective''', ...
    '''RMSEPosMean_km'',''RMSEPosStd_km'',''Position RMSE (km)'',''position_rmse''', ...
    '''EffectiveSigmaPosMean_km'',''EffectiveSigmaPosStd_km'',''Effective position sigma (km)'',''effective_sigma''', ...
    '''MeanStabilityMean'',''MeanStabilityStd'',''Mean stability index'',''stability''', ...
    '''CoverageMean'',''CoverageStd'',''Coverage fraction'',''coverage''', ...
    '''ScreeningMean'',''ScreeningStd'',''Rejected measurement opportunities'',''screening_count''', ...
    '''Baseline AO''', ...
    'matched_baselines', ...
    'results/<study>_<timestamp>/', ...
    'select_reviewer2_representative_runs'});
assert_tokens(figureText,requiredFigures,'Final figure generator');
assert(~contains(figureText,'comparison_6000_runtime'), ...
    '6000-FE comparison runtime should remain table-only.');
assert(~contains(figureText,'baseline_observer_runtime_'), ...
    'Baseline runtime should remain table-only.');
assert(~contains(figureText,'comparison_6000_objective_rank') && ...
    ~contains(figureText,'comparison_6000_mission_wins'), ...
    'Ranking/win summaries should remain table/text results, not redundant figures.');
assert(~contains(figureText,'tiledlayout('), ...
    'Final metrics must be standalone figures for LaTeX assembly.');
assert(~contains(figureText,'uncertainty_band('), ...
    'Final convergence must not use filled uncertainty bands.');

requiredRunner = string({ ...
    'relocate_analysis', ...
    '"runtime_1200"', ...
    '"comparison"', ...
    '"baseline"', ...
    '"objective_screening"', ...
    'yyyyMMdd_HHmmss_SSS', ...
    'movefile', ...
    'make_reviewer2_final_figures(reports,true)', ...
    '20-run mean +/- sample standard deviation', ...
    'run_reviewer2_baseline_monte_carlo separately'});
assert_tokens(runnerText,requiredRunner,'Reviewer 2 results runner');
assert(~contains(runnerText,'paper_final'), ...
    'Final outputs must live directly in timestamped results folders.');
assert(~isfile(fullfile(projectDir,'scripts','make_reviewer2_paper_figures.m')), ...
    'Superseded Reviewer 2 paper renderer still exists.');

fprintf('Reviewer 2 paper-figure configuration passed.\n');
end


function assert_tokens(textValue,tokens,label)
for token = tokens
    assert(contains(textValue,token), ...
        '%s is missing required token: %s',label,token);
end
end