function test_comparison_pipeline_configuration()
%TEST_COMPARISON_PIPELINE_CONFIGURATION Audit the 6000-FE result processor.

projectDir = fileparts(fileparts(mfilename('fullpath')));
pipelineText = string(fileread(fullfile( ...
    projectDir,'scripts','run_reviewer2_comparison_pipeline.m')));
launcherText = string(fileread(fullfile( ...
    projectDir,'scripts','batch','run_comparison_soo.ps1')));
geometryText = string(fileread(fullfile( ...
    projectDir,'scripts','plot_reviewer2_constellation_geometry.m')));

requiredPipeline = string({ ...
    'function report = run_reviewer2_comparison_pipeline(saveFigures)', ...
    'budget = 6000', ...
    'seeds = 0:19', ...
    'optimizers = ["GA","PSO","ABC","ACO"]', ...
    'missions = ["LUNAR_GATEWAY","LOW_THRUST_TRANSFER","GATEWAY_IMPULSE"]', ...
    'studyID = "reviewer2_comparison_v1"', ...
    'comparisonRoot = fullfile(paths.runs,''COMPARISON'')', ...
    'expectedRuns = numel(optimizers)*numel(missions)*numel(seeds)', ...
    'process_fe_convergence', ...
    'plotStartFE = 60', ...
    'comparison_6000_objective', ...
    'comparison_6000_runtime', ...
    'comparison_6000_position_rmse', ...
    'comparison_6000_effective_sigma', ...
    'comparison_6000_coverage', ...
    'comparison_6000_screening_count', ...
    'comparison_6000_stability', ...
    'select_best_geometry_runs', ...
    'plot_reviewer2_constellation_geometry', ...
    'comparison_6000_geometry_selected_runs.csv', ...
    'comparison_6000_geometry_details.csv'});
for token = requiredPipeline
    assert(contains(pipelineText,token), ...
        'Comparison processing pipeline is missing required token: %s',token);
end

% The superseded fixed-design screening diagnostic must be absent. Screening
% sensitivity is now a separate GA optimization study.
obsolete = string({ ...
    'runScreeningSensitivity', ...
    'build_screening_sensitivity', ...
    'SCREENING_SENSITIVITY_GA_6000', ...
    'evaluate_screening_off', ...
    'plot_screening_metric', ...
    'comparison_6000_screening_on_off'});
for token = obsolete
    assert(~contains(pipelineText,token), ...
        'Obsolete post-processing screening diagnostic remains: %s',token);
end

requiredLauncher = string({ ...
    '$StudyId = "reviewer2_comparison_v1"', ...
    '$Algs = @("GA", "PSO", "ABC", "ACO")', ...
    '$MeasurementModels = @("ANGLES_ONLY")', ...
    '$MissionTypes = @("LUNAR_GATEWAY", "LOW_THRUST_TRANSFER", "GATEWAY_IMPULSE")', ...
    '$ObserverCounts = @(3)', ...
    '$GatewayPeriods = @(1)', ...
    '$env:USE_SCREENING = "1"'});
for token = requiredLauncher
    assert(contains(launcherText,token), ...
        'Full comparison launcher is missing required token: %s',token);
end

requiredGeometry = string({ ...
    'uniqueOrbitKeys = unique(orbitKeys,''stable'')', ...
    'period = double(observers.period_TU(member))', ...
    'tPlot = linspace(0,period,300)', ...
    '''LineStyle'',''-''', ...
    'cr3bp_dynamics', ...
    'reviewer2_target_color', ...
    '''Target trajectory''', ...
    '''Observer orbits''', ...
    '''Endpoint orbits''', ...
    'low_thrust_endpoint_orbits', ...
    'find_reference_orbit_for_state', ...
    'plotPosition = [0.15 0.23 0.70 0.56]', ...
    'finalize_centered_geometry_axes', ...
    '1737.1', ...
    'view(ax,-37.5,30)', ...
    'Times New Roman', ...
    'FontSize'',12', ...
    'OrbitFamilies', ...
    'OrbitIndices', ...
    'SlotIndices'});
for token = requiredGeometry
    assert(contains(geometryText,token), ...
        'Constellation geometry exporter is missing required token: %s',token);
end

assert(~contains(geometryText,'earthCenter') && ...
    ~contains(geometryText,'earthRadius') && ...
    ~contains(geometryText,'''Earth'''), ...
    'Earth must be omitted from lunar-region constellation geometry plots.');
assert(~contains(geometryText,'''--'''), ...
    'Constellation geometry panels must not draw dashed trajectory/orbit lines.');

fprintf('Comparison pipeline configuration passed.\n');
end
