function test_baseline_pipeline_configuration()
%TEST_BASELINE_PIPELINE_CONFIGURATION Audit completed baseline processing.

projectDir = fileparts(fileparts(mfilename('fullpath')));
pipelineText = string(fileread(fullfile( ...
    projectDir,'scripts','run_reviewer2_baseline_pipeline.m')));
launcherText = string(fileread(fullfile( ...
    projectDir,'scripts','batch','run_baseline_soo.ps1')));
geometryText = string(fileread(fullfile( ...
    projectDir,'scripts','plot_reviewer2_geometry_grid.m')));

requiredPipeline = string({ ...
    'budget = 6000', ...
    'plotStartFE = 60', ...
    'seeds = 0:19', ...
    'measurements = ["ANGLES_ONLY","ANGLES_RANGE"]', ...
    'missions = ["LUNAR_GATEWAY","LOW_THRUST_TRANSFER","GATEWAY_IMPULSE"]', ...
    'observerCounts = [3 5 7 10]', ...
    'gatewayPeriods = [1 3 5]', ...
    'studyID = "reviewer2_baseline_v1"', ...
    'baselineRoot = fullfile(paths.runs,''BASELINE'')', ...
    'expectedGroups = 2*(4*3 + 4 + 4)', ...
    'expectedRuns = expectedGroups*numel(seeds)', ...
    'expectedConvergenceFigures = numel(missions)*numel(measurements) + numel(measurements)', ...
    'process_fe_convergence', ...
    'validate_baseline_factorial', ...
    'select_baseline_geometry_runs', ...
    'results.Measurement == "ANGLES_ONLY"', ...
    'results.NPeriods == 1', ...
    'plot_observer_count_convergence', ...
    'plot_gateway_period_convergence', ...
    'load_ga_curve', ...
    'plot_baseline_observer_panel', ...
    'plot_baseline_period_panel', ...
    'baseline_6000_trends.csv', ...
    'plot_reviewer2_constellation_geometry', ...
    'baseline_6000_results.csv', ...
    'baseline_6000_geometry_selected_runs.csv', ...
    'baseline_6000_geometry_details.csv'});
assert_tokens(pipelineText,requiredPipeline,'Baseline processing pipeline');

requiredLauncher = string({ ...
    '$StudyId = "reviewer2_baseline_v1"', ...
    '$MeasurementModels = @("ANGLES_ONLY", "ANGLES_RANGE")', ...
    '$ObserverCounts = @(3, 5, 7, 10)', ...
    '$GatewayPeriods = @(1, 3, 5)', ...
    '$env:USE_SCREENING = "1"', ...
    '$env:USE_J1 = "1"', ...
    '$env:USE_J2 = "1"', ...
    '$env:USE_J3 = "1"'});
assert_tokens(launcherText,requiredLauncher,'Baseline launcher');

requiredGeometry = string({ ...
    'function details = plot_reviewer2_geometry_grid', ...
    'panel.uniqueOrbitKeys = unique(panel.orbitKeys,''stable'')', ...
    '''LineStyle'',''-''', ...
    'common_geometry_limits', ...
    'azimuth = -37.5', ...
    'elevation = 30', ...
    'camzoom(ax,0.82)', ...
    'reviewer2_paper_style', ...
    '''Endpoint orbits''', ...
    'low_thrust_endpoint_orbits', ...
    'GridFigureStem'});
assert_tokens(geometryText,requiredGeometry,'Shared constellation geometry exporter');
assert(~contains(geometryText,'earthCenter') && ...
    ~contains(geometryText,'earthRadius') && ...
    ~contains(geometryText,'''Earth'''), ...
    'Earth must be omitted from final baseline geometry plots.');
assert(~contains(geometryText,'''--'''), ...
    'Baseline geometry panels must not draw dashed trajectory/orbit lines.');

assert(2*(4*3+4+4)*20 == 800);
assert(3*2 + 2 == 8,'Baseline convergence layout must contain 8 figures.');
fprintf('Baseline pipeline configuration passed.\n');
end


function assert_tokens(textValue,tokens,label)
for token = tokens
    assert(contains(textValue,token), ...
        '%s is missing required token: %s',label,token);
end
end
