function test_reviewer2_legend_configuration()
%TEST_REVIEWER2_LEGEND_CONFIGURATION Audit manuscript legend behavior.
projectDir = fileparts(fileparts(mfilename('fullpath')));
legendText = string(fileread(fullfile(projectDir,'scripts','format_manuscript_legend.m')));
styleText = string(fileread(fullfile(projectDir,'scripts','reviewer2_paper_style.m')));
studyText = string(fileread(fullfile(projectDir,'scripts','plot_study_definition_figures.m')));
curatedText = string(fileread(fullfile(projectDir,'scripts','make_reviewer2_curated_figures.m')));
geometryText = string(fileread(fullfile(projectDir,'scripts','plot_reviewer2_geometry_grid.m')));

requiredLegend = [ ...
    "lgd.Orientation = 'horizontal'", ...
    "columns = min(numel(labels),style.legendMaxColumns)", ...
    "while lgd.Position(3) > 0.92 && columns > 1", ...
    "columns = columns-1", ...
    "abbreviate_manuscript_text", ...
    "format_manuscript_ticks(ax)"];
assert_tokens(legendText,requiredLegend,'Manuscript legend formatter');
assert(contains(styleText,'style.legendMaxColumns = 8'), ...
    'Legend construction should allow a full row before wrapping.');
assert(contains(studyText,'format_manuscript_legend(ax,legendHandle,style,plotPosition)'), ...
    'Study-definition 3-D figures must use the shared adaptive legend formatter.');
assert(contains(curatedText,'format_manuscript_legend(ax,lgd,style,style.metricPlotPosition)'), ...
    'Curated figures must use the shared adaptive legend formatter.');
assert(contains(geometryText,'format_manuscript_legend(ax,lgd,style,plotPosition)'), ...
    'Representative geometry figures must use the shared adaptive legend formatter.');

fprintf('Reviewer 2 legend configuration passed.\n');
end

function assert_tokens(textValue,tokens,label)
for token = tokens
    assert(contains(textValue,token), ...
        '%s is missing required token: %s',label,token);
end
end
