function color = reviewer2_target_color(mission)
%REVIEWER2_TARGET_COLOR Return the manuscript target-case trajectory color.
%
% These values match the tracking-case introduction figures generated by
% plot_study_definition_figures.m so target trajectories use one consistent
% visual identity throughout the manuscript.

mission = upper(string(mission));
switch mission
    case "LUNAR_GATEWAY"
        color = [0.85,0.27,0.22];
    case "LOW_THRUST_TRANSFER"
        color = [0.27,0.31,0.86];
    case "GATEWAY_IMPULSE"
        impulseBase = [0.55,0.30,0.72];
        postImpulseAlpha = 0.95;
        color = postImpulseAlpha*impulseBase + ...
            (1-postImpulseAlpha)*[1,1,1];
    otherwise
        error('Unknown target case for manuscript color: %s',mission);
end
end
